name: swot_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - affine
  - asttokens
  - attrs
  - blas
  - blosc
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - click
  - click-plugins
  - cligj
  - comm
  - contourpy
  - cycler
  - cyrus-sasl
  - dbus
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - fontconfig
  - fonttools
  - freetype
  - freexl
  - gdal
  - geos
  - geotiff
  - giflib
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - icu
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - json-c
  - jupyter_client
  - jupyter_core
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcups
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libkml
  - libllvm14
  - libnetcdf
  - libnghttp2
  - libpng
  - libpq
  - libsodium
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - minizip
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mysql
  - ncurses
  - nest-asyncio
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - ply
  - poppler
  - poppler-data
  - proj
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - pyparsing
  - pyqt
  - pyqt5-sip
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pyzmq
  - qhull
  - qt-main
  - rasterio
  - readline
  - setuptools
  - sip
  - six
  - snuggs
  - sqlite
  - stack_data
  - tbb
  - tiledb
  - tk
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - unicodedata2
  - uriparser
  - wcwidth
  - wheel
  - xarray
  - xerces-c
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - aiobotocore
      - aiohappyeyeballs
      - aiohttp
      - aioitertools
      - aiosignal
      - async-timeout
      - bcrypt
      - botocore
      - bounded-pool-executor
      - camelot-py
      - cartopy
      - cffi
      - cftime
      - chardet
      - charset-normalizer
      - contextily
      - cryptography
      - earthaccess
      - et-xmlfile
      - fiona
      - frozenlist
      - fsspec
      - fuzzywuzzy
      - geographiclib
      - geopandas
      - geopy
      - ghostscript
      - h5netcdf
      - h5py
      - idna
      - importlib-resources
      - jmespath
      - joblib
      - mercantile
      - multidict
      - multimethod
      - netcdf4
      - opencv-python
      - openpyxl
      - paramiko
      - pdfminer-six
      - pqdm
      - pycparser
      - pykdtree
      - pynacl
      - pyogrio
      - pypdf
      - pyproj
      - pyshp
      - python-cmr
      - rasterstats
      - requests
      - rioxarray
      - s3fs
      - seaborn
      - shapely
      - simplejson
      - tabulate
      - tinynetrc
      - tqdm
      - urllib3
      - wrapt
      - xyzservices
      - yarl
